import { BadRequestException } from "@nestjs/common";
import {
  isShareDekWriteEnabledFor,
  isUserSelectedForRollout,
  parseFlagBoolean,
} from "src/share/share-crypto-scheme";

/**
 * File name schemes.
 *
 * NULL: the file name and its folder path are stored in clear, as on every
 * row written before `File.metadataScheme` existed.
 *
 * FILE_META_V1 (1): the browser encrypts `{ name, relativePath }` with K_share
 * before upload. The server stores the ciphertext in `File.encryptedMetadata`,
 * a fixed placeholder in `File.name` and no folder path. Only SHARE_DEK_V1
 * shares can use it, because K_share is the only key their recipients hold
 * besides the file bytes themselves.
 */
export const FILE_META_V1 = 1;

// Stored in `File.name` and sent as X-File-Name for encrypted rows, it is
// also what logs, e-mails and plain downloads show for them. It is unique per
// file, so that a client without FILE_META_V1 still saves every file.
const ENCRYPTED_FILE_NAME_PREFIX = "encrypted-file-";

export function encryptedFilePlaceholderName(fileId: string): string {
  return `${ENCRYPTED_FILE_NAME_PREFIX}${fileId.slice(0, 8)}`;
}

// base64url [IV 12][ciphertext][GCM tag 16]. The plaintext is padded to a
// multiple of 64 bytes and capped at 4096 bytes, so the encoded value fits in
// one request header everywhere (nginx rejects header lines above 8 KiB).
const IV_BYTES = 12;
const TAG_BYTES = 16;
export const FILE_META_PADDING_BYTES = 64;
export const FILE_META_MAX_PLAINTEXT_BYTES = 4096;
const BASE64URL = /^[A-Za-z0-9_-]+$/;

function decodedBase64UrlLength(value: string): number | null {
  if (value.length % 4 === 1) return null;
  return Math.floor((value.length * 3) / 4);
}

export function isValidEncryptedMetadata(value: unknown): value is string {
  if (typeof value !== "string" || !BASE64URL.test(value)) return false;
  const bytes = decodedBase64UrlLength(value);
  if (bytes === null) return false;
  const plaintext = bytes - IV_BYTES - TAG_BYTES;
  return (
    plaintext >= FILE_META_PADDING_BYTES &&
    plaintext <= FILE_META_MAX_PLAINTEXT_BYTES &&
    plaintext % FILE_META_PADDING_BYTES === 0
  );
}

/**
 * Columns to store for an uploaded file, given the scheme of its share.
 * A share using FILE_META_V1 accepts nothing readable: the client must send
 * the placeholder name, no folder path and a well-formed ciphertext. Any other
 * share refuses encrypted metadata, so that a row can never be half-readable.
 */
export function resolveUploadFileMetadata(
  shareFileMetadataScheme: number | null | undefined,
  file: {
    id?: string;
    name: string;
    relativePath?: string;
    encryptedMetadata?: string;
  },
): {
  name: string;
  relativePath: string | undefined;
  metadataScheme: number | null;
  encryptedMetadata: string | null;
} {
  if (shareFileMetadataScheme === FILE_META_V1) {
    // The ciphertext authenticates the file id chosen by the client: an id
    // generated by the server would make the name impossible to open.
    if (
      !file.id ||
      file.name !== encryptedFilePlaceholderName(file.id) ||
      (file.relativePath !== undefined && file.relativePath !== "") ||
      !isValidEncryptedMetadata(file.encryptedMetadata)
    ) {
      throw new BadRequestException(
        "This share only accepts encrypted file names",
        "file_metadata_required",
      );
    }
    return {
      name: file.name,
      relativePath: undefined,
      metadataScheme: FILE_META_V1,
      encryptedMetadata: file.encryptedMetadata,
    };
  }
  if (
    shareFileMetadataScheme !== null &&
    shareFileMetadataScheme !== undefined
  ) {
    throw new BadRequestException(
      `Unsupported file metadata scheme: ${shareFileMetadataScheme}`,
    );
  }
  if (file.encryptedMetadata !== undefined) {
    throw new BadRequestException(
      "Encrypted file names are not enabled for this share",
      "file_metadata_not_allowed",
    );
  }
  return {
    name: file.name,
    relativePath: file.relativePath,
    metadataScheme: null,
    encryptedMetadata: null,
  };
}

// ----- Feature flag -------------------------------------------------------
//
// FILE_META_V1_WRITE (default false): new SHARE_DEK_V1 shares may encrypt
//   their file names, for the users selected below only. Shares already
//   created with FILE_META_V1 keep accepting files whatever the flag says.
// FILE_META_V1_CANARY_USERS: comma-separated user ids or e-mail addresses,
//   or "*" for every user. Empty selects nobody, even with WRITE=true.
// FILE_META_V1_ROLLOUT_PERCENT (0-100, default 0): additionally selects a
//   stable share of users, from a hash of their id.
//
// A user must also be selected for SHARE_DEK_V1, whose key encrypts the names.

type FlagEnv = Record<string, string | undefined>;

export function isFileMetaWriteEnabledFor(
  user: { id: string; email?: string | null } | null | undefined,
  env: FlagEnv = process.env,
) {
  if (!user) return false;
  if (!isShareDekWriteEnabledFor(user, env)) return false;
  if (!parseFlagBoolean(env.FILE_META_V1_WRITE, false)) return false;
  return isUserSelectedForRollout(
    user,
    env.FILE_META_V1_CANARY_USERS,
    env.FILE_META_V1_ROLLOUT_PERCENT,
    "file-meta-v1",
  );
}
