import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  UnauthorizedException,
} from "@nestjs/common";
import { User } from "@prisma/client";
import { generateSecret, generate, verify, generateURI } from "otplib";
import { createGuardrails } from "@otplib/core";
import * as argon from "argon2";
import * as crypto from "crypto";
import qrcode from "qrcode-svg";
import { ConfigService } from "src/config/config.service";
import { PrismaService } from "src/prisma/prisma.service";
import { AuthService } from "./auth.service";
import { AuthSignInTotpDTO } from "./dto/authSignInTotp.dto";

const BACKUP_CODE_COUNT = 10;

@Injectable()
export class AuthTotpService {
  // Accept legacy 10-byte (80-bit) TOTP secrets stored before otplib v13.
  // New secrets generated by generateSecret() are 20 bytes (160 bits).
  private readonly legacyGuardrails = createGuardrails({
    MIN_SECRET_BYTES: 10,
  });

  constructor(
    private prisma: PrismaService,
    private configService: ConfigService,
    private authService: AuthService,
  ) {}

  // -- Backup code helpers ----------------------------------------

  private generateBackupCodes(): string[] {
    const codes: string[] = [];
    for (let i = 0; i < BACKUP_CODE_COUNT; i++) {
      // 8-char alphanumeric uppercase, e.g. "A1B2C3D4"
      codes.push(crypto.randomBytes(5).toString("hex").toUpperCase().slice(0, 8));
    }
    return codes;
  }

  private async hashAndStoreBackupCodes(
    userId: string,
    codes: string[],
  ): Promise<void> {
    // Delete any existing backup codes for this user
    await this.prisma.totpBackupCode.deleteMany({ where: { userId } });

    // Hash and store all codes
    const records = await Promise.all(
      codes.map(async (code) => ({
        codeHash: await argon.hash(code),
        userId,
      })),
    );

    await this.prisma.totpBackupCode.createMany({ data: records });
  }

  /**
   * Try to match a code against unused backup codes.
   * If matched, marks it as used and returns true.
   */
  private async tryBackupCode(
    userId: string,
    code: string,
  ): Promise<boolean> {
    const unused = await this.prisma.totpBackupCode.findMany({
      where: { userId, usedAt: null },
    });

    for (const entry of unused) {
      if (await argon.verify(entry.codeHash, code.toUpperCase())) {
        await this.prisma.totpBackupCode.update({
          where: { id: entry.id },
          data: { usedAt: new Date() },
        });
        return true;
      }
    }
    return false;
  }

  /**
   * Verify a TOTP code OR a backup code.
   * Returns true if either succeeds.
   */
  private async verifyTotpOrBackup(
    userId: string,
    totpSecret: string,
    code: string,
  ): Promise<boolean> {
    // Try TOTP first (6-digit codes)
    if (/^\d{6}$/.test(code)) {
      const result = await verify({
        secret: totpSecret,
        token: code,
        guardrails: this.legacyGuardrails,
      });
      if (result.valid) return true;
    }

    // Try backup code (8-char alphanumeric)
    return this.tryBackupCode(userId, code);
  }

  // -- Sign in with TOTP -----------------------------------------

  async signInTotp(dto: AuthSignInTotpDTO) {
    const token = await this.prisma.loginToken.findFirst({
      where: {
        token: dto.loginToken,
      },
      include: {
        user: true,
      },
    });

    if (!token || token.used)
      throw new UnauthorizedException("Invalid login token");

    if (token.expiresAt < new Date())
      throw new UnauthorizedException("Login token expired", "token_expired");

    // Check the TOTP code
    const { totpSecret } = token.user;

    if (!totpSecret) {
      throw new BadRequestException("TOTP is not enabled");
    }

    if (!(await this.verifyTotpOrBackup(token.user.id, totpSecret, dto.totp))) {
      throw new BadRequestException("Invalid code");
    }

    // Set the login token to used
    await this.prisma.loginToken.update({
      where: { token: token.token },
      data: { used: true },
    });

    const { refreshToken, refreshTokenId } =
      await this.authService.createRefreshToken(token.user.id);
    const accessToken = await this.authService.createAccessToken(
      token.user,
      refreshTokenId,
    );

    return { accessToken, refreshToken };
  }

  // -- Enable TOTP -----------------------------------------------

  async enableTotp(user: User, password: string) {
    if (!(await this.authService.verifyPassword(user, password)))
      throw new ForbiddenException("Invalid password");

    // Check if we have a secret already
    const { totpVerified } = await this.prisma.user.findUnique({
      where: { id: user.id },
      select: { totpVerified: true },
    });

    if (totpVerified) {
      throw new BadRequestException("TOTP is already enabled");
    }

    const issuer = this.configService.get("general.appName");
    const secret = generateSecret();

    const otpURL = generateURI({
      issuer,
      label: user.username || user.email,
      secret,
    });

    await this.prisma.user.update({
      where: { id: user.id },
      data: {
        totpEnabled: true,
        totpSecret: secret,
      },
    });

    // TODO: Maybe we should generate the QR code on the client rather than the server?
    const qrCode = new qrcode({
      content: otpURL,
      container: "svg-viewbox",
      join: true,
    }).svg();

    return {
      totpAuthUrl: otpURL,
      totpSecret: secret,
      qrCode:
        "data:image/svg+xml;base64," + Buffer.from(qrCode).toString("base64"),
    };
  }

  // -- Verify TOTP (finalize activation + generate backup codes) -

  async verifyTotp(user: User, password: string, code: string) {
    if (!(await this.authService.verifyPassword(user, password)))
      throw new ForbiddenException("Invalid password");

    const { totpSecret } = await this.prisma.user.findUnique({
      where: { id: user.id },
      select: { totpSecret: true },
    });

    if (!totpSecret) {
      throw new BadRequestException("TOTP is not in progress");
    }

    if (!(await verify({ secret: totpSecret, token: code, guardrails: this.legacyGuardrails })).valid) {
      throw new BadRequestException("Invalid code");
    }

    await this.prisma.user.update({
      where: { id: user.id },
      data: {
        totpVerified: true,
      },
    });

    // Generate backup codes and return them in plaintext (only time they're shown)
    const backupCodes = this.generateBackupCodes();
    await this.hashAndStoreBackupCodes(user.id, backupCodes);

    return { backupCodes };
  }

  // -- Disable TOTP (accepts TOTP code OR backup code) -----------

  async disableTotp(user: User, password: string, code: string) {
    if (!(await this.authService.verifyPassword(user, password)))
      throw new ForbiddenException("Invalid password");

    const { totpSecret } = await this.prisma.user.findUnique({
      where: { id: user.id },
      select: { totpSecret: true },
    });

    if (!totpSecret) {
      throw new BadRequestException("TOTP is not enabled");
    }

    if (!(await this.verifyTotpOrBackup(user.id, totpSecret, code))) {
      throw new BadRequestException("Invalid code");
    }

    await this.prisma.$transaction([
      this.prisma.totpBackupCode.deleteMany({ where: { userId: user.id } }),
      this.prisma.user.update({
        where: { id: user.id },
        data: {
          totpVerified: false,
          totpEnabled: false,
          totpSecret: null,
        },
      }),
    ]);

    return true;
  }

  // -- Admin: force-disable TOTP for a user ----------------------

  async adminDisableTotp(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: { totpEnabled: true },
    });

    if (!user) {
      throw new BadRequestException("User not found");
    }

    if (!user.totpEnabled) {
      throw new BadRequestException("TOTP is not enabled for this user");
    }

    await this.prisma.$transaction([
      this.prisma.totpBackupCode.deleteMany({ where: { userId } }),
      this.prisma.user.update({
        where: { id: userId },
        data: {
          totpVerified: false,
          totpEnabled: false,
          totpSecret: null,
        },
      }),
    ]);

    return true;
  }
}
